### ISSUE TITLE
issue during data processing

### ISSUE THREAD

**Issue by tetlika** [homedepot/GoogleBillingDashboard#15]
web_1   | INFO:root:------- GET THE bdg-2016-03-27.csv -- 8c5fc94d214d10.....805f7bfa8------
web_1   | INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/storage/v1/b/my_budget/o/bdg-2016-03-27.csv?alt=json
web_1   | INFO:root:METADATA -- None -- None
web_1   | INFO:root: No lock metadata found  or StartTime was old
web_1   | INFO:googleapiclient.discovery:URL being requested: POST https://www.googleapis.com/storage/v1/b/my_budget/o/bdg-2016-03-27.csv/copyTo/b/my_budget/o/bdg-2016-03-27.csv?alt=json
web_1   | ERROR:root: Error in getting Lock file  -- tuple index out of range
web_1   | INFO:root: bdg-2016-03-27.csv Locked --- Do Nothing -----
web_1   | INFO:root:Process End time --- 2016-03-29 08:40:24.072515
web_1   | INFO:root:Total Time to Process all the files -- (0.0, 8.06427)
web_1   | INFO:root: ARGS PASSED --- cron
web_1   | INFO:apscheduler.executors.default:Job "data_processor (trigger: cron[hour='0-23', minute='0-59', second='16'], next run at: 2016-03-29 08:41:16 UTC)" executed successfully

**Comment by ashpc** [comment]
** Closing because the error is due to bucket write permissions issue **

_ **Related to #14  :** Does the gcloud account need write access to the bucket?_
