### ISSUE TITLE
Project id truncated if value contains hyphen

### ISSUE THREAD

**Issue by envintus** [homedepot/GoogleBillingDashboard#19]
Adding a project with an ID that contains a hyphen results in the new project having an ID of everything before the hyphen. For example adding a value of foo-bar to the project ID field shows a value of just "foo" after saving the project. I see where this is actually taking place in ``cuProjectsControllers.js``, but am unsure if this is supposed to be the intended result.

Snippet of code for reference:
https://github.com/homedepot/GoogleBillingDashboard/blob/6e5bae394966d574d449fa4f53449d67f658f99a/web/billing-app/apps/static/js/controllers/billing/cuProjectsControllers.js#L105

Also, do project ID's or names need to match data that is being imported, parsed, and stored by the scheduler for that data to be displayed under ``/billing``?

**Comment by ashpc** [comment]
Hi,
 Thanks a lot for pointing out this issue related to the projectID, I have fixed this issue in #20. 
As for your question regarding should the project Id's match the JSON file -- yes, they should be the same.

Thanks
Ashwini
